version: '3.8'

services:
  letshare-server:
    build: .
    ports:
      - "8080:8080"
    environment:
      - MODE=production
      - LETSHARE_SERVER_PORT=8080
      - LETSHARE_JWT_SECRET=letshare-jwt-secret-key-2024-docker
      - LETSHARE_LOG_LEVEL=info
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - letshare-network

  # Nginx反向代理（可选）
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - letshare-server
    restart: unless-stopped
    networks:
      - letshare-network

networks:
  letshare-network:
    driver: bridge

volumes:
  logs: 