version: '3.3'

services:
  letshare-server:
    build: .
    ports:
      - "8080:8080"
    environment:
      - MODE=production
      - LETSHARE_SERVER_PORT=8080
      - LETSHARE_JWT_SECRET=letshare-jwt-secret-key-2024-docker
      - LETSHARE_LOG_LEVEL=info
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - letshare-network

networks:
  letshare-network:
    driver: bridge

volumes:
  logs: