server:
  port: "8080"

jwt:
  secret: "letshare-jwt-secret-key-2024-local"
  expiration_hours: 720 # 30天

cors:
  allowed_origins:
    - "http://localhost:3000"
    - "http://localhost:5173" 
    - "http://127.0.0.1:3000"
    - "http://127.0.0.1:5173"
    - "https://letshare.fun"
    - "https://www.letshare.fun"

log:
  level: "debug"
  max_entries: 200

websocket:
  max_room_users: 50 