server:
  port: "443"

tls:
  enabled: true
  cert_file: "/etc/letsencrypt/live/ecs.letshare.fun/fullchain.pem"
  key_file: "/etc/letsencrypt/live/ecs.letshare.fun/privkey.pem"
  auto_cert: true
  domain: "ecs.letshare.fun"

jwt:
  secret: "letshare-jwt-secret-key-2024-production"
  expiration_hours: 720 # 30天

cors:
  allowed_origins:
    - "https://letshare.fun"
    - "https://www.letshare.fun"
    - "https://cdn.letshare.fun"
    - "https://ecs.letshare.fun"

log:
  level: "info"
  max_entries: 200

websocket:
  max_room_users: 50